name: default workflow with maven

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main
         
jobs:
   build:
      runs-on: ${{matrix.os}}
      strategy:
         matrix:
            os: [ubuntu-latest,windows-latest,macos-latest]
      
      steps:
         - name: Clone the repository
           uses: actions/checkout@v4
         - name: Set up JDK 17 on ${{matrix.os}}
           uses: actions/setup-java@v4
           with: 
              java-version: "17"
              distribution: "oracle"
         - name: Cache Maven and SonarQube packages
           uses: actions/cache@v3
           with:
              path: |
                 ~/.m2
                 `/.sonar/cache
              key: ${{matrix.os}}-m2&sonar-${{hashFiles('**/pom.xml', '**/*.yml')}}
              restore-keys: ${{matrix.os}}-m2&sonar-
              
         - name: Build with Maven and SonarCloud
           if: ${{always()}}
           run: "mvn verify -Pcode-coverage,mutation-testing coveralls:report sonar:sonar -Dsonar.organization=merie-san -Dsonar.projectKey=merie-san_snake"
           working-directory: snake
           env:
              SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
              COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
         - name: Archive generated reports
           if: ${{always()}}
           uses: actions/upload-artifact@v4
           with:
              name: reports-os-${{matrix.os}}
              path: |
                 **/target/site
                 **/target/pit-reports
                 **/surefire-reports